#!/bin/bash

if [ ! $EUID = 0 ]; then
    echo "ERROR: Exec with root."
    exit 1
fi

SH_PATH=$(dirname "$0")
APP_PATH=/opt/Wallpaper-LX

# necessary files
APP_FOLDER_PATH=$SH_PATH/app/
RESOURCES_FOLDER_PATH=$SH_PATH/resources/

LANG_JSON=$SH_PATH/lang.json
MAIN=$SH_PATH/main.py
WALLPAPER_LX=$SH_PATH/Wallpaper-LX
APP_DESKTOP=$SH_PATH/wallpaper_lx.desktop

echo "INFO: Starting installation..."

if [ -d $APP_PATH ]; then
    chmod +x "$SH_PATH/uninstall"
    $SH_PATH/uninstall
    echo "INFO: Existing version removed."
fi

mkdir $APP_PATH

IFS=$'\n' read -d '' -ra array <<< "$(cat $SH_PATH/appfiles.txt)"
folderpath=$APP_PATH

# Imprime el contenido del array
for element in "${array[@]}"; do
  if [ -d "$element" ]; then
    folderpath="$APP_PATH/$element"
    mkdir -p "$folderpath"
    echo "INFO: Folder $folderpath created."
  else
    cp "$element" "$folderpath"
    echo "INFO: $element copied to $folderpath."
  fi
done

for element in "${array[@]}"; do
  if [ ! -e "$element" ]; then
    echo "ERROR: The files required for app execution were not copied."
    rm -r -dir --force /opt/Wallpaper-LX
    exit
  fi
done

chmod +x $APP_PATH/Wallpaper-LX

cp "$SH_PATH/icons/16x16/wallpaper-lx.png" /usr/share/icons/hicolor/16x16/apps/
cp "$SH_PATH/icons/32x32/wallpaper-lx.png" /usr/share/icons/hicolor/32x32/apps/
cp "$SH_PATH/icons/48x48/wallpaper-lx.png" /usr/share/icons/hicolor/48x48/apps/
cp "$SH_PATH/icons/128x128/wallpaper-lx.png" /usr/share/icons/hicolor/128x128/apps/
cp "$SH_PATH/icons/256x256/wallpaper-lx.png" /usr/share/icons/hicolor/256x256/apps/

desktop-file-install --dir=/usr/share/applications "$APP_DESKTOP"
echo "INFO: wallpaper_lx.desktop installed."

echo "INFO: App successfully installed."
