#!/bin/bash

if [ ! $EUID = 0 ]; then
  echo "ERROR: Exec with root."
  exit 1
fi

if [ $HOME = /root ]; then
  HOME=/home/$SUDO_USER
fi

# Remove venv files
VENV_PATH=$HOME/.config/Wallpaper-LX/.venv
if [ -d $VENV_PATH ]; then
  rm -r -dir --force $VENV_PATH
  echo "INFO: $VENV_PATH (removed)"
fi

# Remove .desktop and icons
rm --force /usr/share/icons/hicolor/16x16/apps/wallpaper-lx.png
rm --force /usr/share/icons/hicolor/32x32/apps/wallpaper-lx.png
rm --force /usr/share/icons/hicolor/48x48/apps/wallpaper-lx.png
rm --force /usr/share/icons/hicolor/128x128/apps/wallpaper-lx.png
rm --force /usr/share/icons/hicolor/256x256/apps/wallpaper-lx.png

if [ -f /usr/share/applications/wallpaper_lx.desktop ]; then
  rm --force /usr/share/applications/wallpaper_lx.desktop
  echo "INFO: /usr/share/applications/wallpaper_lx.desktop (removed)"
fi

# Remove app files
if [ -d /opt/Wallpaper-LX ]; then
  rm -r -dir --force /opt/Wallpaper-LX
  echo "INFO: App uninstalled."
else
  echo "INFO: The app is not installed."
fi
