#!/bin/bash

SH_PATH=$(dirname "$0")
MAIN_PY=$SH_PATH/main.py

VENV_PATH=$HOME/.config/Wallpaper-LX
ACTIVATE_PATH=$VENV_PATH/bin/activate

[ ! -d $VENV_PATH ] && python3 -m venv $VENV_PATH
[ ! -f $ACTIVATE_PATH ] && python3 -m venv $VENV_PATH

if [ ! -f $ACTIVATE_PATH ]; then
    echo venv error. Possibly python3-venv is not installed on your system.
    exit
fi

source $ACTIVATE_PATH

pip3 install pillow

python3 -u $MAIN_PY
deactivate
