#!/bin/bash

SH_PATH=$(dirname "$0")
MAIN_PY=$SH_PATH/main.py

VENV_PATH=$HOME/.config/Wallpaper-LX/.venv
ACTIVATE_PATH=$VENV_PATH/bin/activate

INSTALL_MODULES=false

if [ ! -d $VENV_PATH ]; then
  python3 -m venv $VENV_PATH
  INSTALL_MODULES=true
fi
if [ ! -f $ACTIVATE_PATH ]; then
  python3 -m venv $VENV_PATH
  INSTALL_MODULES=true
fi
if [ ! -f $ACTIVATE_PATH ]; then
  echo venv error. Possibly python3-venv is not installed on your system.
  exit 1
fi

source $ACTIVATE_PATH

if [ $INSTALL_MODULES = true ]; then
  pip3 install pillow
fi

python3 -u $MAIN_PY

if [ ! $? = 0 ]; then
  deactivate

  rm -r -dir --force $VENV_PATH

  python3 -m venv $VENV_PATH
  source $ACTIVATE_PATH

  pip3 install pillow

  python3 -u $MAIN_PY
fi

deactivate
